[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "1da2e6d6eef8a7a8937f3a6bc1fdf75e119cc539"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "3c6bee337b40828c5791af2b1069b666304a9cd9eb69aa7f2ad123080995b122"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+aarch64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "64957fa5ffc35bda90be0ed3de62d69ba7739f2c"
libc = "glibc"
os = "linux"
target_arch = "i686"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "2a5e47a275243da4b98a29b6764eab71b99bae9925c3a811c16b9945ae4dfee2"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+i686.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "cd19afa4e8e2008054f2d62d4f4cb1e6d76eaf90"
libc = "glibc"
os = "linux"
target_arch = "powerpc64le"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "432b6e4d8ccd2b8afd87fac0e028345ed68dbf5b219f6cea037294e09efd375f"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+powerpc64le.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "55fea015ffc9e616b3ff401f7269c2165ae60fb3"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "983e5fafe4a155e82e04966a31b1b614733e9cd108b64b7eefe1493cb0543a20"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "1e7de8b4fcbb84e99aa78a602dd33320bfcee4d2"
libc = "glibc"
os = "linux"
target_arch = "armv6l"
target_call_abi = "eabihf"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "85beadc435b08aa50f778f4df7ebbe932fdc311b4e3179f2b6cdc7a216305a59"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_call_abi+eabihf-target_arch+armv6l.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "911134073b753b434fa14c7a69e73f3a5af9f3bb"
libc = "glibc"
os = "linux"
target_arch = "armv7l"
target_call_abi = "eabihf"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "9bc3b02f81791e0530481cbf600ee19eef33233fc6dbb75fe9995c838b33ff47"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_call_abi+eabihf-target_arch+armv7l.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "639606cfcd280f3cb516db5456593151f8c23d22"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "2dc4c23a4330f468cd306bce7537e8f5d6a26c7878479c0904c2b04136498a3f"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-gnu-target_libc+musl-target_os+linux-target_arch+aarch64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "f318a45cd4abed59ccf20ed536ab2467e02bebc9"
libc = "glibc"
os = "linux"
target_arch = "i686"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "41915cdb3df677ddafc10aa736d1f6c3fdbc7d9a4287b0bcc754cc83c92ea048"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-gnu-target_libc+musl-target_os+linux-target_arch+i686.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "f2904b8a0af82e3484268cc7af23fd8919be2b62"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "9992674c92ff49dbaa63ec78dbc4a411d16019b7bd5cb6cdb5f484944fd91ac4"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-gnu-target_libc+musl-target_os+linux-target_arch+x86_64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "8ce2af3294b6884dde4d2f209b8c500185604bc9"
libc = "glibc"
os = "linux"
target_arch = "armv6l"
target_call_abi = "eabihf"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "d1886e467e2a9a02d1f9d0d9858f54c22fab55f09eabf0e9eab007a2b64cc349"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-gnu-target_libc+musl-target_os+linux-target_call_abi+eabihf-target_arch+armv6l.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "9ad73655d8101803e97885122ea12d3a8bca35aa"
libc = "glibc"
os = "linux"
target_arch = "armv7l"
target_call_abi = "eabihf"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "f768dce4e1f5831d430943c6acc66ea8b452d754302983196b001547a8ab87df"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-gnu-target_libc+musl-target_os+linux-target_call_abi+eabihf-target_arch+armv7l.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "aa9e9acc4d8fff227fde6106dd6639d8cc5fe0ce"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[Binutils.download]]
    sha256 = "90e2f6a247c8127bd1c04efcbbac1b51704c4a3d17485b403aca2564fa63bcee"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-gnu-target_os+freebsd-target_arch+x86_64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "1dd25b4719c2a5d8f34c9e3efbee2f16fc18229c"
libc = "glibc"
os = "linux"
target_arch = "i686"
target_os = "windows"

    [[Binutils.download]]
    sha256 = "93a0aa2a1291b83c0a300945bec48f313454eac5eebb0c8e2d1fb5ee375f01e4"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-gnu-target_os+windows-target_arch+i686.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "7eb0b0dfb67df8bf69f854525032dfeec1410cf8"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "windows"

    [[Binutils.download]]
    sha256 = "108263dc2b2edb34748b095ef7ea852b9e1149bce8d57eefdc4f53ceb59bac10"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-gnu-target_os+windows-target_arch+x86_64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "8233b9c584c2e142d2d288e8cecdb7754f0f5a01"
libc = "musl"
os = "linux"
target_arch = "aarch64"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "39490955bea0e8a9f8a2fcaa7adbc76a58e6904f458f109e4721ab0b0b78aa0e"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-musl-target_libc+glibc-target_os+linux-target_arch+aarch64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "5c903c12c6fd90730a7703294fab5df8684e165b"
libc = "musl"
os = "linux"
target_arch = "i686"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "f68fbcf85c870cd184a7447eedfc528d18c901c6a7683f6372ba5d8c4422baf9"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-musl-target_libc+glibc-target_os+linux-target_arch+i686.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "8dc865a988e1c9e9ccaa957c96945f18dc99b671"
libc = "musl"
os = "linux"
target_arch = "powerpc64le"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "1fba8b6920f7757b3fcb39ab6ce35ff2cdec01b77da0576ce83737dee2ab8c56"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-musl-target_libc+glibc-target_os+linux-target_arch+powerpc64le.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "fe8d1c373a9d00e00fdca8097b8330cd339d9868"
libc = "musl"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "27e776bf4f8cd802713253a425cea9ca2e637232b0f14289578fbbf45c80a449"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-musl-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "4d58e973f691349ffcc365d307c96efe50297eb2"
libc = "musl"
os = "linux"
target_arch = "armv6l"
target_call_abi = "eabihf"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "ab82a30ecc18b9867c145b2390210b6a323b85c24e79ef4201c23062b7a544b3"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-musl-target_libc+glibc-target_os+linux-target_call_abi+eabihf-target_arch+armv6l.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "74eadf5d75ed2b5b31f4238972ac0e41efefadef"
libc = "musl"
os = "linux"
target_arch = "armv7l"
target_call_abi = "eabihf"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "7d5fc503b55c59ed75b5ab12a56da80de902d15af8f8d7d657010dbd8afd5983"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-musl-target_libc+glibc-target_os+linux-target_call_abi+eabihf-target_arch+armv7l.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "9c313ca6c8b05309e3a9a1155b5d0662f14cbbdb"
libc = "musl"
os = "linux"
target_arch = "aarch64"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "d0446613af08d1dec95fbcd8f72db89f405a487aeb7587ae3bff676eecacc870"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-musl-target_libc+musl-target_os+linux-target_arch+aarch64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "14a4d2b6fb29fca81a9304e118f858532d15bb03"
libc = "musl"
os = "linux"
target_arch = "i686"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "a1b2b297e6f1bb0594968e0f4a2f670f9696b824e6a3a6d9ef3141a550e1cfac"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-musl-target_libc+musl-target_os+linux-target_arch+i686.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "451769ea8ebf0d14d7d65cab1fb9c8a6645557b7"
libc = "musl"
os = "linux"
target_arch = "x86_64"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "da9c091a893e88dccd6d8142a8ed0912bd1fc3d045bd7f4fd99805bb7190b3f1"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-musl-target_libc+musl-target_os+linux-target_arch+x86_64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "3b7adc961b0c4c1180f27b2b7e8ec83f37e0a51e"
libc = "musl"
os = "linux"
target_arch = "armv6l"
target_call_abi = "eabihf"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "153609618dab8afec85cfff73d74111aebf03972e4a5f50dd5bac4b119c206cf"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-musl-target_libc+musl-target_os+linux-target_call_abi+eabihf-target_arch+armv6l.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "859d8facb574f6176e9104ed49cca6d1a13b86f8"
libc = "musl"
os = "linux"
target_arch = "armv7l"
target_call_abi = "eabihf"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "6dc2a4f50a79ac8c4265900fdf983b0f6ef0e70b9fee72d78ace3a1a8b0a5730"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-musl-target_libc+musl-target_os+linux-target_call_abi+eabihf-target_arch+armv7l.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "7aa48eac42d08e4c85401fc7ec1e31ff9fd340a2"
libc = "musl"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[Binutils.download]]
    sha256 = "c82299a03c54a5c92e38ec88baab43c4e01d353671b814136bfb6cbdb6049195"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-musl-target_os+freebsd-target_arch+x86_64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "4f71dabbcb81fb2e679f68ef668d558c747d7fe7"
libc = "musl"
os = "linux"
target_arch = "i686"
target_os = "windows"

    [[Binutils.download]]
    sha256 = "77e11e0d180f751b186e9ac42c651dd1bfa823644a2ba82144a28a4c4297d565"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-musl-target_os+windows-target_arch+i686.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "073c692d5c31b6fd70d7c1e29103ecb171d63fca"
libc = "musl"
os = "linux"
target_arch = "x86_64"
target_os = "windows"

    [[Binutils.download]]
    sha256 = "2fb681d041cf010a5c1051bdebbe0c63231888790bc22ca0ead143c388bde979"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.24.0+2/Binutils.v2.24.0.x86_64-linux-musl-target_os+windows-target_arch+x86_64.tar.gz"
