[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "a471e7c2d76c85807774733bba08da0c9efdfb4a"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "2d97101d2ec0c850c4112c090d4bb77135ffdf21c379391c23746abf84572249"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+aarch64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "b2d04461abfc12b7a03ef8396ac88faf1104269a"
libc = "glibc"
os = "linux"
target_arch = "i686"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "885ff83d931119e736c262b8b41c9dcb02a50786e0ba47dc5be1711611e73959"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+i686.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "1907aa7ca045fcb3f47c09808fd24da7f28de8fa"
libc = "glibc"
os = "linux"
target_arch = "powerpc64le"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "b7cbec6322497b2f2f6ea249e21b4b6af33c406df17ea7454ee3dd01b5490212"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+powerpc64le.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "eadffe4df35d5b8f3b1dabc3f684c677b9776808"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "148e86943a8653ef8b9773e545cc1d653f7b5f9afe6542a05323ab6132ad96c2"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "3d836a31c50991d112b49a464d8a7d04694e70e9"
libc = "glibc"
os = "linux"
target_arch = "armv6l"
target_call_abi = "eabihf"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "df818a25333d8a3df22b7482e8dd8507751fd8fd9fb9f66aa95be87180d742f1"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_call_abi+eabihf-target_arch+armv6l.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "3371675a5497dd45b2480dfccfb86e7b313a4c2e"
libc = "glibc"
os = "linux"
target_arch = "armv7l"
target_call_abi = "eabihf"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "0d23048e3268bd888ad73bbd1283fc9266ae71970fd73eb8a99a02bcbc81bcfd"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-gnu-target_libc+glibc-target_os+linux-target_call_abi+eabihf-target_arch+armv7l.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "fd84dafbfb15acc5b7fa07aa9133e8522b15bdb7"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "849f2a56084209472bd247b30ddd02ad34a3e36ed94200158937485c794bceb2"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-gnu-target_libc+musl-target_os+linux-target_arch+aarch64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "726e4572d6c3c393d4cf45daa668e2a8e75ffc9b"
libc = "glibc"
os = "linux"
target_arch = "i686"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "35e45a8d9e5e678e2e31afbd09ad4a7c71c9a02c45f854a77c9c5c954fa3668b"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-gnu-target_libc+musl-target_os+linux-target_arch+i686.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "cbc2ca91f617345141719ded14ecc769e7843dfc"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "660d13511d78f215717da57bf5c4361232f4c9bc1d4fc9579dd4c0c1e83ea1ee"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-gnu-target_libc+musl-target_os+linux-target_arch+x86_64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "09d5f2e58fab3c0a63b77ef91be61f8ca3a43fd8"
libc = "glibc"
os = "linux"
target_arch = "armv6l"
target_call_abi = "eabihf"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "98b5f3de4a826789cb8fc4c4d2bcc84259c5e9b626838d3150a083726ef80c4a"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-gnu-target_libc+musl-target_os+linux-target_call_abi+eabihf-target_arch+armv6l.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "1a264a20144e8d8c1c755554963f6d274166af1f"
libc = "glibc"
os = "linux"
target_arch = "armv7l"
target_call_abi = "eabihf"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "f5efaa19d7c0f430db21d81c0650aa5403926afd8b14284f86d49b8b73980a67"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-gnu-target_libc+musl-target_os+linux-target_call_abi+eabihf-target_arch+armv7l.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "f7ba277e33327f906fa20a7a9dfb1a8de9d3f1b8"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[Binutils.download]]
    sha256 = "9df390095c000aa301c5c70878164e365165cba7fc9dbcf02f59d31a6d6b7a2d"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-gnu-target_os+freebsd-target_arch+x86_64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "6173c2a13667a0d449a15ee310782662071c097e"
libc = "glibc"
os = "linux"
target_arch = "i686"
target_os = "windows"

    [[Binutils.download]]
    sha256 = "1cdd73e98a37573f3c1764b2bc1133a7e6cb4269fbcf96e895c0caf6fd274bb9"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-gnu-target_os+windows-target_arch+i686.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "9496059d86d8325003ad443d34d020d2b59669d1"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "windows"

    [[Binutils.download]]
    sha256 = "56f820a4289bd6c2fb547dbfbe921d20e80a8a15c8148b1f08bdbc87a535efa9"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-gnu-target_os+windows-target_arch+x86_64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "d3fb9ed751a21c80f7827273820cbc16036f192a"
libc = "musl"
os = "linux"
target_arch = "aarch64"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "32ca7dcfbf92e3ecb58b4ad7f76ec3298548680320001822896065d0f25a22ac"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-musl-target_libc+glibc-target_os+linux-target_arch+aarch64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "b2304b756d4e9da3ff79453dcdb7f6be90cc1d74"
libc = "musl"
os = "linux"
target_arch = "i686"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "b4d4e32f10616b87ffce23a959a86f343d855e907c014cfbcfb105e6478f540d"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-musl-target_libc+glibc-target_os+linux-target_arch+i686.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "d260f3abccf071e52e0040d622c7558a19af7162"
libc = "musl"
os = "linux"
target_arch = "powerpc64le"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "958b73081ba3fb0495e6247606e9ed9e798b26d71ed81f52ff3ea53fa6abffa2"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-musl-target_libc+glibc-target_os+linux-target_arch+powerpc64le.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "4de666a60f665c5d140b45a63b93dd9088949c37"
libc = "musl"
os = "linux"
target_arch = "x86_64"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "7c608d5a25a360468896e399ecf68863e48b771793b33b3a4451bd00169a1cfc"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-musl-target_libc+glibc-target_os+linux-target_arch+x86_64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "c35ca5e69e1b84143391da9e35e2b470b6984d88"
libc = "musl"
os = "linux"
target_arch = "armv6l"
target_call_abi = "eabihf"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "282736eaeb7725fe4bcbe694ef4a7c196f3d5ac7d97908f8e396711eb0716708"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-musl-target_libc+glibc-target_os+linux-target_call_abi+eabihf-target_arch+armv6l.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "b80f4007b103ac45bd71f324e6e1b0e0e65e61ad"
libc = "musl"
os = "linux"
target_arch = "armv7l"
target_call_abi = "eabihf"
target_libc = "glibc"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "439593f87afd784193d8fb89f07ab40a2c054bb4ff5d13e209d38d987f0c5e9f"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-musl-target_libc+glibc-target_os+linux-target_call_abi+eabihf-target_arch+armv7l.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "e284d00e444497565ee39dfd7fc53eb7d0e2e711"
libc = "musl"
os = "linux"
target_arch = "aarch64"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "cb7512eb9fb16acb606396886939d791e4ab1dd33b9352c299b711787e8f129f"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-musl-target_libc+musl-target_os+linux-target_arch+aarch64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "4e290622931bb60c3504b24bbd0c89f49d4ffdfc"
libc = "musl"
os = "linux"
target_arch = "i686"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "7b1245311f48a46ce60a6abf120d9c6e86fbf358df0fab0fe46d86deb56bedc0"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-musl-target_libc+musl-target_os+linux-target_arch+i686.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "fcb2d9e22c252fcab350dbea2b8732693eb21840"
libc = "musl"
os = "linux"
target_arch = "x86_64"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "7c99a1b687b12b8b1fb4744fb6bfdeda71c497d83bef2c84dfaf006147b396a5"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-musl-target_libc+musl-target_os+linux-target_arch+x86_64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "97adff6ab3b2ec84bfa06e2b3d45996fcdb3d74a"
libc = "musl"
os = "linux"
target_arch = "armv6l"
target_call_abi = "eabihf"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "f5f33b387c3177dd60b6d9bbec4665fec9d18bddcf6fa2b42cc26c4cd82303d8"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-musl-target_libc+musl-target_os+linux-target_call_abi+eabihf-target_arch+armv6l.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "a62536b9777b54341427e50469b4729fc75ef158"
libc = "musl"
os = "linux"
target_arch = "armv7l"
target_call_abi = "eabihf"
target_libc = "musl"
target_os = "linux"

    [[Binutils.download]]
    sha256 = "67fcc4a5390e34ff2b627847463b29dbd53199b741b1aebfa9901f57c945e530"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-musl-target_libc+musl-target_os+linux-target_call_abi+eabihf-target_arch+armv7l.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "de17a1c66e5fc5cf454af4cf041ef52a3d0d83ab"
libc = "musl"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[Binutils.download]]
    sha256 = "70400c2655939344e2fd5e4179720d7df52d6741ee53e0f1303e2ae0cb68aaa4"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-musl-target_os+freebsd-target_arch+x86_64.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "3e06997dffb90d6fc0f38b27bc74d0a956deea6f"
libc = "musl"
os = "linux"
target_arch = "i686"
target_os = "windows"

    [[Binutils.download]]
    sha256 = "908a7e5bb85a4abe20d8c72321d0946f7742c0aa2e4260fa525051da23bea1a8"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-musl-target_os+windows-target_arch+i686.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "71389d5467bf0b5efc7ee3aace2369175350e2e6"
libc = "musl"
os = "linux"
target_arch = "x86_64"
target_os = "windows"

    [[Binutils.download]]
    sha256 = "d362496301e8d1f87ce6564c59b5ee46c1347a5a566de393c6cf433aaa906b21"
    url = "https://github.com/staticfloat/Binutils_jll.jl/releases/download/Binutils-v2.38.0+0/Binutils.v2.38.0.x86_64-linux-musl-target_os+windows-target_arch+x86_64.tar.gz"
